# What is NumPy?

**NumPy** (Numerical Python) is a Python library used for fast numerical computations. It gives us the **array** (`ndarray`) object — similar to a Python list, but much faster and built for doing math on large amounts of data at once.

In this notebook, we learn NumPy step-by-step by analyzing a dataset of **500 students** (their age, marks in Math/Science/English, and hours studied). By the end, we will calculate each student's **Total Score, Average, Pass/Fail Result, Grade, and CGPA**.

## 1. Importing Libraries

We need two libraries:
- `numpy` — for fast array operations and math.
- `pandas` — for reading and handling the CSV file as a table (DataFrame).

In [1]:
import numpy as np
import pandas as pd

## 2. Loading the Dataset

We load `student_data.csv` using `pandas.read_csv()`. This gives us a DataFrame (a table), and `.shape` tells us how many rows and columns it has.

In [2]:
# load the data
data = pd.read_csv("student_data.csv")

print("Shape of the data :")
data.shape

Shape of the data :

(500, 6)

## 3. Exploring the Dataset

Before working with the data, let's check its structure with `.info()` (column names, data types, missing values) and `.head()` (first 5 rows).

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student_ID     500 non-null    int64
 1   Age            500 non-null    int64
 2   Math_Score     500 non-null    int64
 3   Science_Score  500 non-null    int64
 4   English_Score  500 non-null    int64
 5   Hours_Studied  500 non-null    float64
dtypes: float64(1), int64(5)
memory usage: 23.6 KB

In [4]:
data.head()

   Student_ID  Age  Math_Score  Science_Score  English_Score  Hours_Studied
0           1   16          62             49             44            7.5
1           2   17          52             40             63            2.3
2           3   15          39             67             90            2.9
3           4   17          98             35             64            8.4
4           5   17          63             52             93            3.9

## 4. Converting Columns to NumPy Arrays

Right now our data lives inside a pandas DataFrame. To use NumPy functions directly, we pull out each column with `.values`, which converts a pandas column (Series) into a NumPy array.

We check the `type`, `shape`, and `dtype` of each array:
- **type** → confirms it is a NumPy array (`ndarray`)
- **shape** → `(500,)` means 500 values in a single row (1D array)
- **dtype** → `int64` means whole numbers, `float64` means decimal numbers

In [5]:
# convert each column into numpy
age = data["Age"].values
science_score = data["Science_Score"].values
english_score = data["English_Score"].values
hour_studied = data["Hours_Studied"].values
math_score = data["Math_Score"].values

print("-------------------------------------------------------------------------------------------------")
print("Data Loaded !")
print(f"Type : {type(age)}")
print(f"Shape : {age.shape} - means 500 values in one row.")
print(f"dtype : {age.dtype} int64 means whole numbers")
print()
print("First 10 age scores:", age[:10])

print("-------------------------------------------------------------------------------------------------")
print("Data Loaded !")
print(f"Type : {type(science_score)}")
print(f"Shape : {science_score.shape} - means 500 values in one row.")
print(f"dtype : {science_score.dtype} int64 means whole numbers")
print()
print("First 10 science_score scores:", science_score[:10])

print("-------------------------------------------------------------------------------------------------")
print("Data Loaded !")
print(f"Type : {type(english_score)}")
print(f"Shape : {english_score.shape} - means 500 values in one row.")
print(f"dtype : {english_score.dtype} int64 means whole numbers")
print()
print("First 10 english_score scores:", english_score[:10])

print("-------------------------------------------------------------------------------------------------")
print("Data Loaded !")
print(f"Type : {type(hour_studied)}")
print(f"Shape : {hour_studied.shape} - means 500 values in one row.")
print(f"dtype : {hour_studied.dtype} int64 means whole numbers")
print()
print("First 10 hour_studied scores:", hour_studied[:10])

print("-------------------------------------------------------------------------------------------------")
print("Data Loaded !")
print(f"Type : {type(math_score)}")
print(f"Shape : {math_score.shape} - means 500 values in one row.")
print(f"dtype : {math_score.dtype} int64 means whole numbers")
print()
print("First 10 math_score scores:", math_score[:10])
print("-------------------------------------------------------------------------------------------------")

-------------------------------------------------------------------------------------------------
Data Loaded !
Type : <class 'numpy.ndarray'>
Shape : (500,) - means 500 values in one row.
dtype : int64 int64 means whole numbers

First 10 age scores: [16 17 15 17 17 14 15 15 15 17]
-------------------------------------------------------------------------------------------------
Data Loaded !
Type : <class 'numpy.ndarray'>
Shape : (500,) - means 500 values in one row.
dtype : int64 int64 means whole numbers

First 10 science_score scores: [49 40 67 35 52 76 75 41 42 91]
-------------------------------------------------------------------------------------------------
Data Loaded !
Type : <class 'numpy.ndarray'>
Shape : (500,) - means 500 values in one row.
dtype : int64 int64 means whole numbers

First 10 english_score scores: [44 63 90 64 93 54 53 41 47 44]
-------------------------------------------------------------------------------------------------
Data Loaded !
Type : <class 'numpy.ndarray'>
Shape : (500,) - means 500 values in one row.
dtype : float64 int64 means whole numbers

First 10 hour_studied scores: [7.5 2.3 2.9 8.4 3.9 1.2 2.4 3.  9.6 6.2]
-------------------------------------------------------------------------------------------------
Data Loaded !
Type : <class 'numpy.ndarray'>
Shape : (500,) - means 500 values in one row.
dtype : int64 int64 means whole numbers

First 10 math_score scores: [62 52 39 98 63 81 39 48 87 30]
-------------------------------------------------------------------------------------------------

## 5. Basic Array Operations

NumPy lets us do math on an entire array at once — no loops needed. This is called **broadcasting**.
- Adding a number to every score (bonus marks)
- Dividing to get a percentage
- Adding three arrays together to get a total score

In [6]:
# add 5 bonus marks in math
math_bonous = math_score + 5
print("Math_Score before adding bonus :", math_score[:5])
print("Math_Score after  adding bonus :", math_bonous[:5])

# check the percentage
math_percentage = math_score / 100 * 100
print("Math_score as percentage:", math_percentage[:5])

print()

# total score = math + science + english
total_score = math_score + science_score + english_score
print("Total score :", total_score[:5])
print("Max possible total score : 300")

Math_Score before adding bonus : [62 52 39 98 63]
Math_Score after  adding bonus : [ 67  57  44 103  68]
Math_score as percentage: [62. 52. 39. 98. 63.]

Total score : [155 155 196 197 208]
Max possible total score : 300

## 6. Descriptive Statistics

NumPy has built-in functions for common statistics: `np.mean()`, `np.median()`, `np.std()` (standard deviation), `np.min()`, `np.max()`, and `np.sum()`.

In [7]:
print("MATH SCORE STATISTICS")
print(f" Mean (Average) : {np.mean(math_score):.2f}")
print(f" Median : {np.median(math_score):.2f}")
print(f" Std Deviation : {np.std(math_score):.2f}")
print(f" Minimum Score : {np.min(math_score):.2f}")
print(f" Maximum Score : {np.max(math_score):.2f}")
print(f" Total Sum      : {np.sum(math_score):.2f}")
print("--"*35)

print("ENGLISH SCORE STATISTICS")
print(f" Mean (Average) : {np.mean(english_score):.2f}")
print(f" Median : {np.median(english_score):.2f}")
print(f" Std Deviation : {np.std(english_score):.2f}")
print(f" Minimum Score : {np.min(english_score):.2f}")
print(f" Maximum Score : {np.max(english_score):.2f}")
print(f" Total Sum      : {np.sum(english_score)}")
print("--"*35)

print("SCIENCE SCORE STATISTICS")
print(f" Mean (Average) : {np.mean(science_score):.2f}")
print(f" Median : {np.median(science_score):.2f}")
print(f" Std Deviation : {np.std(science_score):.2f}")
print(f" Minimum Score : {np.min(science_score):.2f}")
print(f" Maximum Score : {np.max(science_score):.2f}")
print(f" Total Sum      : {np.sum(science_score)}")
print("--"*35)

# NOTE: original notebook printed the English block twice by mistake.
# Hours Studied gets its own stats here instead.
print("HOURS STUDIED STATISTICS")
print(f" Mean (Average) : {np.mean(hour_studied):.2f}")
print(f" Median : {np.median(hour_studied):.2f}")
print(f" Std Deviation : {np.std(hour_studied):.2f}")
print(f" Minimum Score : {np.min(hour_studied):.2f}")
print(f" Maximum Score : {np.max(hour_studied):.2f}")
print(f" Total Sum      : {np.sum(hour_studied):.2f}")
print("--"*35)

MATH SCORE STATISTICS
 Mean (Average) : 63.60
 Median : 63.00
 Std Deviation : 20.54
 Minimum Score : 30.00
 Maximum Score : 100.00
 Total Sum      : 31802.00
----------------------------------------------------------------------
ENGLISH SCORE STATISTICS
 Mean (Average) : 63.84
 Median : 64.00
 Std Deviation : 20.17
 Minimum Score : 30.00
 Maximum Score : 100.00
 Total Sum      : 31920
----------------------------------------------------------------------
SCIENCE SCORE STATISTICS
 Mean (Average) : 64.86
 Median : 65.50
 Std Deviation : 20.18
 Minimum Score : 30.00
 Maximum Score : 100.00
 Total Sum      : 32428
----------------------------------------------------------------------
HOURS STUDIED STATISTICS
 Mean (Average) : 5.41
 Median : 5.40
 Std Deviation : 2.63
 Minimum Score : 1.00
 Maximum Score : 10.00
 Total Sum      : 2704.90
----------------------------------------------------------------------

## 7. Sorting and Finding Extremes

`np.sort()` arranges values from lowest to highest. `np.argmax()` and `np.argmin()` give the **position (index)** of the highest/lowest value, not the value itself.

In [8]:
# Sort Math Score from lowest to highest
sorted_math = np.sort(math_score)
print("5 lowest Math scores:", sorted_math[:5])
print("5 highest Math scores:", sorted_math[-5:])

print()

# Find who got the highest math score (their position in the list)
top_student_index = np.argmax(math_score)
print(f"Student at index {top_student_index} got highest Math Score: {math_score[top_student_index]}")

lowest_student_index = np.argmin(math_score)
print(f"Student at index {lowest_student_index} got lowest Math Score: {math_score[lowest_student_index]}")

5 lowest Math scores: [30 30 30 30 30]
5 highest Math scores: [ 99  99  99 100 100]

Student at index 72 got highest Math Score: 100
Student at index 9 got lowest Math Score: 30

## 8. Boolean Filtering (Conditions on Arrays)

We can use conditions like `math_score > 80` directly on a NumPy array. This creates a **boolean mask** (True/False for each student), which we can then use to filter or count.

In [9]:
# Students who scored above 80 in Math
high_score = math_score[math_score > 80]
print(f"Students Scoring above 80 in maths: {len(high_score)} students.")
print("Their Scores (First 10)", high_score[:10])

print()

# Students who studied more than 7hr
hard_working = hour_studied[hour_studied > 7]
print(f"Students who studied more than 7hrs : {len(hard_working)} students.")

print()

# Students who scored above 80 in math and science
top_In_both = (math_score > 80) & (science_score > 80)
print(f"Students scoring > 80 in both math and science : {np.sum(top_In_both)}")

# Students scoring above 80 in english and math
top_in_both = (math_score > 80) & (english_score > 80)
print(f"Students topped in both math and english: {np.sum(top_in_both)}")

Students Scoring above 80 in maths: 130 students.
Their Scores (First 10) [98 81 87 98 90 96 94 97 87 93]

Students who studied more than 7hrs : 163 students.

Students scoring > 80 in both math and science : 36
Students topped in both math and english: 25

## 9. Combining Multiple Conditions

The `&` operator combines two conditions — both must be `True` for a student to be counted. This lets us ask more specific questions, like *students who scored high AND studied a lot*.

In [ ]:
# Students who scored above 80 in math and studied more than 8 hr
mix_value = (math_score > 80) & (hour_studied > 8)
print(f"Students Who scored above 80 in math and studied more than 8 hr is : {np.sum(mix_value)}")

# Students who scored above 80 in english and studied more than 8 hr
mix_value1 = (english_score > 80) & (hour_studied > 8)
print(f"Students Who scored above 80 in english and studied more than 8 hr is : {np.sum(mix_value1)}")

# Students who scored above 80 in science and studied more than 8 hr
mix_value = (science_score > 80) & (hour_studied > 8)
print(f"Students Who scored above 80 in science and studied more than 8 hr is : {np.sum(mix_value)}")

Students Who scored above 80 in math and studied more than 8 hr is : 21
Students Who scored above 80 in english and studied more than 8 hr is : 26
Students Who scored above 80 in science and studied more than 8 hr is : 29

## 10. Stacking Arrays & Understanding `axis`

`np.column_stack()` combines three 1D arrays into one 2D array, where each row is a student and each column is a subject.

The `axis` parameter decides the direction of the calculation:
- **`axis=0`** → calculates **down each column** → one result **per subject**
- **`axis=1`** → calculates **across each row** → one result **per student**

This is a common point of confusion, so we calculate both and compare.

In [11]:
# Stack all three subject scores as columns -> gives a 2D array
# Each row = one student, each column = one subject (Math, English, Science)
score_2D = np.column_stack([math_score, english_score, science_score])

print("Shape of 2D array:", score_2D.shape)
print("500 rows (students), 3 columns (Subjects)\n")

print("First 5 rows (Students):")
print("Math | English | Science")
print(score_2D[:5])

print()

# Average score per SUBJECT (axis=0 goes DOWN the columns)
subject_avg = np.mean(score_2D, axis=0)
print("Average by Subject:")
print(f"Math    : {subject_avg[0]:.2f}")
print(f"English : {subject_avg[1]:.2f}")
print(f"Science : {subject_avg[2]:.2f}")

print()

# Average score per STUDENT (axis=1 goes ACROSS the row)
student_avg = np.mean(score_2D, axis=1)
print("Average by Student (first 5 students):")
print(np.round(student_avg[:5], 2))

Shape of 2D array: (500, 3)
500 rows (students), 3 columns (Subjects)

First 5 rows (Students):
Math | English | Science
[[62 44 49]
 [52 63 40]
 [39 90 67]
 [98 64 35]
 [63 93 52]]

Average by Subject:
Math    : 63.60
English : 63.84
Science : 64.86

Average by Student (first 5 students):
[51.67 51.67 65.33 65.67 69.33]

## 11. Reshaping Arrays

`np.reshape()` changes the *shape* of an array without changing its data or order. The total number of elements must stay the same (here, 24 numbers, either as 6×4 or 4×6).

In [12]:
# Create a single 1D array of 24 numbers
arr = np.arange(1, 25)  # [1,2,3,........,24]
print("Original 1D array :", arr)
print("Shape:", arr.shape)

# reshape into 6 rows x 4 columns
arr_2d = arr.reshape(6, 4)
print("Reshape to 6x4:")
print(arr_2d)

print()

# reshape into 4 rows x 6 columns
arr_2d1 = arr.reshape(4, 6)
print("Reshape to 4x6:")
print(arr_2d1)
print()

Original 1D array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)
Reshape to 6x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Reshape to 4x6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

## 12. More Useful NumPy Functions

- `np.unique()` → lists all distinct values, no repeats
- `np.percentile()` → finds the value below which a given percentage of the data falls
- `np.clip()` → caps values within a min/max range
- `np.where()` → works like an if-else, applied to a whole array at once

In [13]:
# np.unique() to find all unique values (no repeats)
unique_ages = np.unique(age)
print("Unique ages in our data", unique_ages)

# np.percentile() like "top X%"
p25 = np.percentile(math_score, 25)  # 25th percentile
p75 = np.percentile(math_score, 75)  # 75th percentile
print("Math score percentile: ")
print(f"25th percentile: {p25} - Bottom 25% scored below this")
print(f"75th percentile: {p75} - Top 25% scored above this")

print()

# np.clip() limits values between a min and max
# Let's say the max score allowed is 95
math_capped = np.clip(math_score, 0, 95)
print(f"Original math max score: {np.max(math_score)}")
print(f"Original math max capped: {np.max(math_capped)}")

# np.where() works like if-else for arrays:
# give grade "Pass" if score is >= 50, else "Fail"
result = np.where(math_score >= 50, "Pass", "Fail")
pass_count = np.sum(result == "Pass")
fail_count = np.sum(result == "Fail")
print("Math Pass/Fail:")
print(f" Pass: {pass_count} students")
print(f" Fail: {fail_count} students")

Unique ages in our data [13 14 15 16 17 18]
Math score percentile:
25th percentile: 46.0 - Bottom 25% scored below this
75th percentile: 81.0 - Top 25% scored above this

Original math max score: 100
Original math max capped: 95
Math Pass/Fail:
 Pass: 348 students
 Fail: 152 students

## 13. Repeating the Analysis for English

Let's apply the same `clip()` and `where()` logic to the English scores.

In [14]:
# np.clip() limits values between a min and max
# Let's say the max score allowed is 95
english_capped = np.clip(english_score, 0, 95)
print(f"Original english max score: {np.max(english_score)}")
print(f"Original english max capped: {np.max(english_capped)}")

# np.where() works like if-else for arrays:
# give grade "Pass" if score is >= 50, else "Fail"
result = np.where(english_score >= 50, "Pass", "Fail")
pass_count = np.sum(result == "Pass")
fail_count = np.sum(result == "Fail")
print("english Pass/Fail:")
print(f" Pass: {pass_count} students")
print(f" Fail: {fail_count} students")

Original english max score: 100
Original english max capped: 95
english Pass/Fail:
 Pass: 354 students
 Fail: 146 students

## 14. Correlation Analysis

`np.corrcoef()` returns a **correlation matrix**. The value at position `[0,1]` tells us how strongly two variables move together, from **-1** (opposite) to **+1** (move together perfectly). We check if **hours studied** is linked to performance in each subject.

In [15]:
# Correlation
# np.corrcoef() gives a correlation matrix
# we want: correlation between hours studied and math score

core_matrix = np.corrcoef(hour_studied, math_score)
correlation = core_matrix[0, 1]  # top right value in the 2x2 matrix

print(f"Correlation between hours studied and math score: {correlation:.4f}")
print()

if correlation > 0.5:
    print("Strong positive link - Studying more = better math!")
elif correlation > 0.2:
    print("Weak positive link - slight trend, but not strong.")
else:
    print("Very weak/no link - hours studied alone may not predict score")

Correlation between hours studied and math score: -0.0428

Very weak/no link - hours studied alone may not predict score

In [16]:
# Correlation
# np.corrcoef() gives a correlation matrix
# we want: correlation between hours studied and english score

core_matrix = np.corrcoef(hour_studied, english_score)
correlation = core_matrix[0, 1]  # top right value in the 2x2 matrix

print(f"Correlation between hours studied and english score: {correlation:.4f}")
print()

if correlation > 0.5:
    print("Strong positive link - Studying more = better english!")
elif correlation > 0.2:
    print("Weak positive link - slight trend, but not strong.")
else:
    print("Very weak/no link - hours studied alone may not predict score")

Correlation between hours studied and english score: -0.0214

Very weak/no link - hours studied alone may not predict score

In [17]:
# Correlation
# np.corrcoef() gives a correlation matrix
# we want: correlation between hours studied and science score

core_matrix = np.corrcoef(hour_studied, science_score)
correlation = core_matrix[0, 1]  # top right value in the 2x2 matrix

print(f"Correlation between hours studied and science score: {correlation:.4f}")
print()

if correlation > 0.5:
    print("Strong positive link - Studying more = better science!")
elif correlation > 0.2:
    print("Weak positive link - slight trend, but not strong.")
else:
    print("Very weak/no link - hours studied alone may not predict score")

Correlation between hours studied and science score: 0.0214

Very weak/no link - hours studied alone may not predict score

## 15. Final Results: Total Score, Average, Result, Grade & CGPA

Now we bring everything together into the final results table:
- **Total Score** — sum of all three subjects (max 300)
- **Average Score** — `student_avg` from Step 10 (mean per student), rounded to 2 decimals
- **Result** — `Pass` if average ≥ 50, else `Fail`
- **Grade** — letter grade based on average score
- **CGPA** — grade point on a 4.0 scale, following Nepal's standard NEB grading scale:

| Average Score | Grade | CGPA |
|---|---|---|
| 90–100 | A+ | 4.0 |
| 80–89  | A  | 3.6 |
| 70–79  | B+ | 3.2 |
| 60–69  | B  | 2.8 |
| 50–59  | C+ | 2.4 |
| 40–49  | C  | 2.0 |
| 30–39  | D+ | 1.6 |
| 20–29  | D  | 1.2 |
| 0–19   | F  | 0.0 |

Finally, we save everything to `student_results.csv`.

In [18]:
data["Total Score"] = total_score
data["Average Score"] = np.round(student_avg, 2)
data["Result"] = np.where(student_avg >= 50, "Pass", "Fail")

# Assign letter grades
def assign_grade(avg):
    if avg >= 90: return "A+"
    elif avg >= 80: return "A"
    elif avg >= 70: return "B+"
    elif avg >= 60: return "B"
    elif avg >= 50: return "C+"
    elif avg >= 40: return "C"
    elif avg >= 30: return "D+"
    elif avg >= 20: return "D"
    else: return "F"

data["Grade"] = [assign_grade(a) for a in student_avg]

# Assign CGPA (grade point on a 4.0 scale, same score brackets as Grade)
def assign_cgpa(avg):
    if avg >= 90: return 4.0
    elif avg >= 80: return 3.6
    elif avg >= 70: return 3.2
    elif avg >= 60: return 2.8
    elif avg >= 50: return 2.4
    elif avg >= 40: return 2.0
    elif avg >= 30: return 1.6
    elif avg >= 20: return 1.2
    else: return 0.0

data["CGPA"] = [assign_cgpa(a) for a in student_avg]

# Save to a new CSV
data.to_csv("student_results.csv", index=False)

print("Final result saved to student_results.csv!")
print()
print("Grade Distribution:")
print(data["Grade"].value_counts().sort_index())
print()
print(f"Average CGPA of all students: {np.mean(data['CGPA'].values):.2f}")
print()
print("First 5 rows of final data with all columns:")
data.head()

Final result saved to student_results.csv!

Grade Distribution:
Grade
A      41
A+      4
B     165
B+    114
C      46
C+    118
D+     12
Name: count, dtype: int64

Average CGPA of all students: 2.77

First 5 rows of final data with all columns:

,Student_ID,Age,Math_Score,Science_Score,English_Score,Hours_Studied,Total Score,Average Score,Result,Grade,CGPA
0,1,16,62,49,44,7.5,155,51.67,Pass,C+,2.4
1,2,17,52,40,63,2.3,155,51.67,Pass,C+,2.4
2,3,15,39,67,90,2.9,196,65.33,Pass,B,2.8
3,4,17,98,35,64,8.4,197,65.67,Pass,B,2.8
4,5,17,63,52,93,3.9,208,69.33,Pass,B,2.8